// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DB.WeatherX.PwrTls.Models
{
    public partial class ForeVsReal
    {
        public int Id { get; set; }
        public string ForeSiteId { get; set; } = null!;
        public string RealSiteId { get; set; } = null!;
        public double TempAirFore { get; set; }
        public double? TempAirReal { get; set; }
        public DateTime ForecastedAt { get; set; }
        public DateTime ForecastedFor { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public DateTime DevDbgDate { get; set; }
        public DateTime DevDbgDtTm2 { get; set; }
        public DateTimeOffset DevDbgDtoffset { get; set; }
        public string? Note { get; set; }
    }
}