// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DB.WeatherX.PwrTls.Models
{
    public partial class LkuSite
    {
        public string Id { get; set; } = null!;
        public string Name32 { get; set; } = null!;
        public string? FreeNtext { get; set; }
        public DateTimeOffset CreatedAt { get; set; }
    }
}