global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Linq;
global using System.Net.Http;
global using System.Net.Http.Json;
global using System.Threading.Tasks;
global using System.Xml.Serialization;
global using OpenWeather2022.Response;
global using XSD.CLS;
global using static System.Diagnostics.Trace;
global using HtmlAgilityPack;
