global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using System.Windows.Media;
global using System.Windows.Media.Imaging;
global using System.Windows.Threading;
global using CI.Standard.Lib.Helpers;
global using DB.WeatherX.PwrTls.Models;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Toolkit.Mvvm.ComponentModel;
global using Microsoft.Toolkit.Mvvm.Input;
global using OpenWeather2022;
global using OpenWeather2022.Response;
global using OxyPlot;
global using OxyPlot.Axes;
global using OxyPlot.Series;
global using XSD.CLS;
global using static System.Diagnostics.Trace;
global using static System.Media.SystemSounds;
global using static OpenWeather2022.OpenWea;
