global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Text.RegularExpressions;
global using System.Threading.Tasks;
global using System.Windows;
//global using OpenWeaSvc.Response;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Input;
//global using System.Windows.Media;
global using System.Windows.Media.Imaging;
global using System.Windows.Threading;
global using AmbienceLib;
global using AsLink;
//global using System.Windows.Media;
global using Db.EventLog.DbModel;
//obal using System.Text.Json; //tu: new and very performant Json lib (Dec 2021)
global using Db.EventLog.Main;
global using Microsoft.Extensions.Configuration;
global using RadarPicCollect;
global using StandardLib.Extensions;
global using StandardLib.Helpers;
global using WpfUserControlLib.Extensions;
global using static System.Diagnostics.Trace;
